PULP_APP = test
PULP_APP_CXX_SRCS = cxxstring.cpp test.cpp

PULP_CFLAGS = -O3 -g -Wall -Wextra -Wconversion -pedantic # -std=c11
PULP_CXXFLAGS = -O3 -g -Wall -Wextra -Wconversion -Wnoexcept -pedantic -std=c++11

include $(PULPRT_HOME)/rules/pulp.mk
